Repository dialpad/dialtone-vue, pull requests merged in 2023-04, with the labels that each got.

#889 fix(recipe-contact-info): remove d-of-hidden
  components/list_item/default_list_item.vue
Labels: no-visual-test

#891 fix(recipe-contact-info): remove d-of-hidden - vue3
  components/list_item/default_list_item.vue
Labels: no-visual-test

#893 docs: add rich text editor tech spec
  components/rich_text_editor/rich_text_editor.tech_spec.md
Labels: vue2-only

#892 chore: fix visual test flaky avatars
  .github/workflows/visual_tests.yml
  components/combobox/combobox_default.story.vue
  components/skeleton/skeleton_variants.story.vue
  components/tooltip/tooltip_variants.vue
  percy.config.js
  recipes/comboboxes/combobox_multi_select/combobox_multi_select.vue
  recipes/comboboxes/combobox_multi_select/combobox_multi_select_default.story.vue
  recipes/comboboxes/combobox_with_popover/combobox_with_popover.vue
  recipes/comboboxes/combobox_with_popover/combobox_with_popover_default.story.vue
  visual_testing/avatar.stories.js
  visual_testing/banner.stories.js
  visual_testing/combobox_multi_select.mdx
  visual_testing/combobox_multi_select.stories.js
  visual_testing/combobox_with_popover.mdx
  visual_testing/combobox_with_popover.stories.js
  visual_testing/dropdown.stories.js
  visual_testing/image_viewer.stories.js
  visual_testing/inline_components.mdx
  visual_testing/modal.stories.js
  visual_testing/popover.stories.js
  visual_testing/skeleton.stories.js
  visual_testing/toast.stories.js
  visual_testing/tooltip.stories.js
Labels: visual-test-ready

#885 feat(feed-items): create feed item time pill
  generator-dialtone-vue/generators/app/index.js
  recipes/conversation_view/time_pill/index.js
  recipes/conversation_view/time_pill/time_pill.mdx
  recipes/conversation_view/time_pill/time_pill.stories.js
  recipes/conversation_view/time_pill/time_pill.test.js
  recipes/conversation_view/time_pill/time_pill.vue
  recipes/conversation_view/time_pill/time_pill_constants.js
  recipes/conversation_view/time_pill/time_pill_default.story.vue
  visual_testing/inline_components.mdx
Labels: visual-test-ready

#897 fix(popover): losing focus - vue3
  components/popover/popover.vue
Labels: no-visual-test

#894 chore: fix visual test flaky avatars
  .github/workflows/visual_tests.yml
  components/avatar/avatar.stories.js
  components/combobox/combobox_default.story.vue
  components/skeleton/skeleton_variants.story.vue
  components/tooltip/tooltip_variants.vue
  package-lock.json
  package.json
  percy.config.js
  recipes/comboboxes/combobox_multi_select/combobox_multi_select.vue
  recipes/comboboxes/combobox_multi_select/combobox_multi_select_default.story.vue
  recipes/comboboxes/combobox_with_popover/combobox_with_popover.vue
  recipes/comboboxes/combobox_with_popover/combobox_with_popover_default.story.vue
  visual_testing/avatar.stories.js
  visual_testing/banner.stories.js
  visual_testing/combobox_multi_select.mdx
  visual_testing/combobox_multi_select.stories.js
  visual_testing/combobox_with_popover.mdx
  visual_testing/combobox_with_popover.stories.js
  visual_testing/dropdown.stories.js
  visual_testing/image_viewer.stories.js
  visual_testing/inline_components.mdx
  visual_testing/modal.stories.js
  visual_testing/popover.stories.js
  visual_testing/skeleton.stories.js
  visual_testing/toast.stories.js
  visual_testing/tooltip.stories.js
Labels: visual-test-ready

#899 chore: more visual test issues
  .github/workflows/visual_tests.yml
  components/avatar/avatar_presence.story.vue
  components/chip/chip_default.story.vue
  components/dropdown/dropdown.vue
  components/dropdown/dropdown_default.story.vue
  components/dropdown/dropdown_variants.story.vue
  components/popover/popover_variants.story.vue
  visual_testing/dropdown.stories.js
  visual_testing/popover.stories.js
Labels: visual-test-ready

#898 chore: fix more visual test issues
  .github/workflows/visual_tests.yml
  components/avatar/avatar_presence.story.vue
  components/chip/chip_default.story.vue
  components/dropdown/dropdown.vue
  components/dropdown/dropdown_default.story.vue
  components/dropdown/dropdown_variants.story.vue
  components/popover/popover_variants.story.vue
  visual_testing/dropdown.stories.js
  visual_testing/popover.stories.js
Labels: visual-test-ready

#881 feat: support multiple avatars for `DtRecipeContactInfo` Component
  components/avatar/avatar.vue
  recipes/list_items/contact_info/avatar2.png
  recipes/list_items/contact_info/contact_info.vue
  recipes/list_items/contact_info/contact_info_variants.story.vue
Labels: visual-test-ready

#901 fix: showing both image and initials issue
  components/avatar/avatar.vue
Labels: visual-test-ready

#902 fix: showing both image and initials issue (vue3)
  components/avatar/avatar.vue
Labels: visual-test-ready

#900 fix(tooltip): arrow not displaying - vue3
  components/button/button.vue
  css/dialtone-globals.less
Labels: vue3-only, visual-test-ready

#904 fix: null protection on some refs
  components/popover/popover.vue
  recipes/comboboxes/combobox_multi_select/combobox_multi_select.vue
  recipes/comboboxes/combobox_with_popover/combobox_with_popover.vue
Labels: visual-test-ready

#908 fix(avatar): image size and z-index issues
  components/avatar/avatar.stories.js
  components/avatar/avatar.vue
Labels: visual-test-ready

#909 fix(avatar): image size and z-index issues - vue3
  components/avatar/avatar.stories.js
  components/avatar/avatar.vue
Labels: visual-test-ready

#910 fix(recipe-callbar-tooltip): fixed tooltip positioning in the callbar
  recipes/buttons/callbar_button/callbar_button.vue
Labels: visual-test-ready

#913 fix(recipe-callbar-ai-popover): fixed popover positioning in the callbar
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover.vue
Labels: visual-test-ready

#912 fix(recipe-callbar-ai-popover): fixed popover positioning in the callbar
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover.vue
Labels: visual-test-ready

#906 fix(avatar): remove box sizing for overlay text/icon
  components/avatar/avatar.stories.js
  components/avatar/avatar.vue
  components/avatar/avatar_default.story.vue
  components/avatar/avatar_icon.story.vue
  recipes/list_items/contact_info/contact_info.vue
  recipes/list_items/contact_info/contact_info_variants.story.vue
Labels: visual-test-ready

#907 fix(avatar): remove box sizing for overlay text/icon (vue3)
  components/avatar/avatar.stories.js
  components/avatar/avatar.vue
  components/avatar/avatar_default.story.vue
  components/avatar/avatar_icon.story.vue
  recipes/list_items/contact_info/contact_info.vue
  recipes/list_items/contact_info/contact_info_variants.story.vue
Labels: visual-test-ready

#914 fix: remove dialtone-icons from externals
  vue.config.js
Labels: no-visual-test

#916 fix(leftbar_row): animation speed to 1.5s
  recipes/leftbar/style/leftbar_row.less
Labels: no-visual-test

#918 fix: emoji size in leftbar item descriptions
  recipes/leftbar/general_row/general_row.vue
Labels: visual-test-ready

#917 fix(leftbar-row): animation speed to 1.5s
  recipes/leftbar/style/leftbar_row.less
Labels: no-visual-test

#919 fix: emoji size in leftbar item descriptions
  recipes/leftbar/general_row/general_row.vue
Labels: visual-test-ready

#905 feat(rich-text-editor): add rich text editor component
  components/rich_text_editor/index.js
  components/rich_text_editor/rich_text_editor.mdx
  components/rich_text_editor/rich_text_editor.stories.js
  components/rich_text_editor/rich_text_editor.tech_spec.md
  components/rich_text_editor/rich_text_editor.vue
  components/rich_text_editor/rich_text_editor_constants.js
  components/rich_text_editor/rich_text_editor_default.story.vue
  package-lock.json
  package.json
Labels: visual-test-ready

#924 test(rich-text-editor): add tests for rich text editor
  components/rich_text_editor/rich_text_editor.test.js
  components/rich_text_editor/rich_text_editor.vue
Labels: visual-test-ready

#927 fix(image-viewer): image viewer improvements vue3
  components/image_viewer/image_viewer.vue
Labels: visual-test-ready

#926 fix(image-viewer): image viewer improvements
  components/image_viewer/image_viewer.vue
Labels: visual-test-ready

#933 fix: visual tests not triggering on approval
  .github/workflows/visual_tests.yml
Labels: visual-test-ready

#934 fix: visual tests not triggering on approval
  .github/workflows/visual_tests.yml
Labels: visual-test-ready

#923 refactor(root-layout): remove javascript - vue3
  components/root_layout/index.js
  components/root_layout/root_layout.mdx
  components/root_layout/root_layout.stories.js
  components/root_layout/root_layout.test.js
  components/root_layout/root_layout.vue
  components/root_layout/root_layout_body.test.js
  components/root_layout/root_layout_body.vue
  components/root_layout/root_layout_constants.js
  components/root_layout/root_layout_default.story.vue
  components/root_layout/root_layout_sticky.story.vue
  package-lock.json
  package.json
  visual_testing/inline_components.mdx
Labels: visual-test-ready

#922 refactor(root-layout): remove javascript
  components/root_layout/index.js
  components/root_layout/root_layout.mdx
  components/root_layout/root_layout.stories.js
  components/root_layout/root_layout.test.js
  components/root_layout/root_layout.vue
  components/root_layout/root_layout_body.test.js
  components/root_layout/root_layout_body.vue
  components/root_layout/root_layout_constants.js
  components/root_layout/root_layout_default.story.vue
  components/root_layout/root_layout_sticky.story.vue
  package-lock.json
  package.json
  visual_testing/inline_components.mdx
Labels: visual-test-ready

#929 fix: channels icons size 200 instead of 300
  recipes/leftbar/general_row/general_row.stories.js
  recipes/leftbar/general_row/general_row.vue
  recipes/leftbar/general_row/general_row_constants.js
  recipes/leftbar/general_row/general_row_default.story.vue
  recipes/leftbar/general_row/index.js
  recipes/leftbar/general_row/leftbar_general_row_icon.vue
  recipes/leftbar/unread_chip/unread_chip.stories.js
Labels: visual-test-ready

#930 fix: channels icons size 200 instead of 300
  recipes/leftbar/general_row/general_row.stories.js
  recipes/leftbar/general_row/general_row.vue
  recipes/leftbar/general_row/general_row_constants.js
  recipes/leftbar/general_row/general_row_default.story.vue
  recipes/leftbar/general_row/index.js
  recipes/leftbar/general_row/leftbar_general_row_icon.vue
  recipes/leftbar/unread_chip/unread_chip.stories.js
Labels: visual-test-ready

#931 fix(recipe-callbar-button-with-popover): update margin for callbutton with popover when in compact mode
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover.vue
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover_variants.story.vue
Labels: visual-test-ready

#932 fix(recipe-callbar-button-with-popover): update margin for callbutton…
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover.vue
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover_variants.story.vue
Labels: visual-test-ready

#944 chore: enable only inline component tests
  percy.config.js
  recipes/cards/ivr_node/ivr_node_default.story.vue
  recipes/list_items/contact_info/contact_info.stories.js
  recipes/list_items/contact_info/contact_info.vue
  recipes/list_items/contact_info/contact_info_default.story.vue
  visual_testing/inline_components.stories.js
Labels: visual-test-ready

#942 feat: deploy to GitHub packages
  .github/workflows/deploy.yml
Labels: no-visual-test

#943 feat: deploy to GitHub packages
  .github/workflows/deploy.yml
Labels: no-visual-test

#937 feat(header): add setting menu button with update option
  index.js
  recipes/header/settings_menu_button/index.js
  recipes/header/settings_menu_button/settings_menu_button.mdx
  recipes/header/settings_menu_button/settings_menu_button.stories.js
  recipes/header/settings_menu_button/settings_menu_button.vue
  recipes/header/settings_menu_button/settings_menu_button_default.story.vue
Labels: visual-test-ready

#945 chore: enable only inline component tests
  percy.config.js
  recipes/cards/ivr_node/ivr_node_default.story.vue
  recipes/list_items/contact_info/contact_info.stories.js
  recipes/list_items/contact_info/contact_info.vue
  recipes/list_items/contact_info/contact_info_default.story.vue
  visual_testing/inline_components.stories.js
Labels: visual-test-ready

#925 feat(feed-item-row): recipe for feed item row
  common/assets/fry.gif
  common/assets/person.png
  components/avatar/avatar.stories.js
  components/avatar/avatar_presence.story.vue
  components/image_viewer/image_viewer_variants.story.vue
  components/list_item/default_list_item.vue
  index.js
  recipes/cards/ivr_node/ivr_node.mdx
  recipes/conversation_view/feed_item_row/feed_item_row.mdx
  recipes/conversation_view/feed_item_row/feed_item_row.stories.js
  recipes/conversation_view/feed_item_row/feed_item_row.vue
  recipes/conversation_view/feed_item_row/feed_item_row_constants.js
  recipes/conversation_view/feed_item_row/feed_item_row_default.story.vue
  recipes/conversation_view/feed_item_row/feed_item_row_variants.story.vue
  recipes/conversation_view/feed_item_row/index.js
  recipes/leftbar/contact_row/contact_row.mdx
  recipes/leftbar/contact_row/contact_row.stories.js
  recipes/leftbar/contact_row/contact_row_variants.story.vue
  recipes/leftbar/group_row/group_row_variants.story.vue
Labels: visual-test-ready

#947 feat(header): add setting menu button with update option
  index.js
  recipes/header/settings_menu_button/index.js
  recipes/header/settings_menu_button/settings_menu_button.mdx
  recipes/header/settings_menu_button/settings_menu_button.stories.js
  recipes/header/settings_menu_button/settings_menu_button.vue
  recipes/header/settings_menu_button/settings_menu_button_default.story.vue
Labels: visual-test-ready
