Repository dialpad/dialtone-vue, pull requests merged in 2023-08, with the labels that each got.

#1110 fix(leftbar-row): avatar presence color on selected row
  recipes/leftbar/style/leftbar_row.less
Labels: visual-test-ready

#1108 feat: add typescript
  .storybook/main.js
  env.d.ts
  package-lock.json
  package.json
  tsconfig.config.json
  tsconfig.json
Labels: no-visual-test

#1109 feat: add typescript - vue3
  .storybook/main.js
  env.d.ts
  package-lock.json
  package.json
  tsconfig.config.json
  tsconfig.json
Labels: no-visual-test

#1111 feat(avatar): add icon-class prop
  components/avatar/avatar.vue
  components/avatar/avatar_default.story.vue
Labels: visual-test-ready

#1112 feat(avatar): add icon-class prop - vue3
  components/avatar/avatar.vue
  components/avatar/avatar_default.story.vue
Labels: visual-test-ready

#1115 fix(avatar): overlay icon alignment
  components/avatar/avatar.vue
  components/avatar/avatar_variants.story.vue
  components/chip/chip.stories.js
  components/chip/chip_default.story.vue
Labels: visual-test-ready

#1116 fix(avatar): overlay icon alignment - vue3
  components/avatar/avatar.vue
  components/avatar/avatar_variants.story.vue
  components/chip/chip.stories.js
  components/chip/chip_default.story.vue
Labels: visual-test-ready

#1121 feat: update theme variables in dt-vue
  package-lock.json
  package.json
  recipes/header/settings_menu_button/settings_menu_button.vue
  recipes/leftbar/contact_row/contact_row.stories.js
  recipes/leftbar/general_row/general_row.stories.js
  recipes/leftbar/group_row/group_row.stories.js
  recipes/leftbar/style/leftbar_row.less
  recipes/leftbar/unread_pill/unread_pill.stories.js
  recipes/leftbar/unread_pill/unread_pill.vue
Labels: visual-test-ready

#1122 feat: update theme variables in dt-vue
  package-lock.json
  package.json
  recipes/header/settings_menu_button/settings_menu_button.vue
  recipes/leftbar/contact_row/contact_row.stories.js
  recipes/leftbar/general_row/general_row.stories.js
  recipes/leftbar/group_row/group_row.stories.js
  recipes/leftbar/style/leftbar_row.less
  recipes/leftbar/unread_pill/unread_pill.stories.js
  recipes/leftbar/unread_pill/unread_pill.vue
Labels: visual-test-ready

#1119 docs: update documentation
  .github/CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: no-visual-test

#1120 docs: update documentation - vue3
  .github/CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: no-visual-test

#1117 test(checkbox, icon): new test template - vue3
  .github/CONTRIBUTING.md
  .github/TEST_CONTRIBUTING/TEST_GUIDELINE.md
  .github/TEST_CONTRIBUTING/test_template.js
  components/checkbox/checkbox.test.js
  components/icon/icon.test.js
Labels: no-visual-test

#1124 test(avatar, badge): new test template - vue3
  components/avatar/avatar.test.js
  components/badge/badge.test.js
Labels: no-visual-test

#1123 test(avatar, badge): new test template
  components/avatar/avatar.test.js
  components/badge/badge.test.js
Labels: no-visual-test

#1125 fix(select-menu): pass event object onChange
  components/select_menu/select_menu.test.js
  components/select_menu/select_menu.vue
Labels: visual-test-ready, no-visual-test

#1126 fix(select-menu): pass event object onChange
  components/select_menu/select_menu.test.js
  components/select_menu/select_menu.vue
Labels: visual-test-ready

#1127 test(breadcrumb, breadcrumb-item, button): new test template
  components/breadcrumbs/breadcrumb.test.js
  components/breadcrumbs/breadcrumb_item.test.js
  components/button/button.test.js
Labels: no-visual-test

#1128 test(breadcrumb - breadcrumb-item - button): new test template - vue3
  components/breadcrumbs/breadcrumb.test.js
  components/breadcrumbs/breadcrumb_item.test.js
  components/button/button.test.js
Labels: no-visual-test

#1132 fix(recipe-callbar-button-with-popover): do not autofocus on the popover
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover.vue
Labels: visual-test-ready

#1129 feat(callbox): scaffold component
  index.js
  recipes/leftbar/callbox/callbox.mdx
  recipes/leftbar/callbox/callbox.stories.js
  recipes/leftbar/callbox/callbox.test.js
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_constants.js
  recipes/leftbar/callbox/callbox_default.story.vue
  recipes/leftbar/callbox/callbox_variants.story.vue
  recipes/leftbar/callbox/index.js
Labels: no-visual-test

#1130 feat(callbox): scaffold component - vue3
  index.js
  recipes/leftbar/callbox/callbox.mdx
  recipes/leftbar/callbox/callbox.stories.js
  recipes/leftbar/callbox/callbox.test.js
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_constants.js
  recipes/leftbar/callbox/callbox_default.story.vue
  recipes/leftbar/callbox/callbox_variants.story.vue
  recipes/leftbar/callbox/index.js
Labels: no-visual-test

#1133 fix(select-menu): emit value first
  components/select_menu/select_menu.test.js
  components/select_menu/select_menu.vue
Labels: no-visual-test

#1134 fix(select-menu): emit value first
  components/select_menu/select_menu.test.js
  components/select_menu/select_menu.vue
Labels: visual-test-ready

#1137 fix(contact-info): avatar's border color
  recipes/list_items/contact_info/contact_info.vue
Labels: visual-test-ready

#1138 fix(contact-info): avatar's border color - vue 3
  recipes/list_items/contact_info/contact_info.vue
Labels: visual-test-ready

#1141 test(button-group, card, checkbox-group): new test template
  components/button_group/button_group.test.js
  components/card/card.test.js
  components/checkbox_group/checkbox_group.test.js
Labels: no-visual-test

#1139 refactor(callbox): visuals
  recipes/leftbar/callbox/callbox.mdx
  recipes/leftbar/callbox/callbox.stories.js
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_default.story.vue
  recipes/leftbar/callbox/callbox_variants.story.vue
Labels: visual-test-ready

#1140 refactor(callbox): visuals - vue3
  recipes/leftbar/callbox/callbox.mdx
  recipes/leftbar/callbox/callbox.stories.js
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_default.story.vue
  recipes/leftbar/callbox/callbox_variants.story.vue
Labels: visual-test-ready

#1148 docs(chip): variants story
  .github/workflows/visual_tests.yml
  .storybook/main.js
  components/chip/chip.mdx
  components/chip/chip.stories.js
  components/chip/chip_default.story.vue
  components/chip/chip_variants.story.vue
  percy.config.cjs
Labels: visual-test-ready

#1149 docs(chip): variants story - vue3
  .github/workflows/visual_tests.yml
  .storybook/main.js
  components/chip/chip.mdx
  components/chip/chip.stories.js
  components/chip/chip_default.story.vue
  components/chip/chip_variants.story.vue
  percy.config.cjs
Labels: visual-test-ready

#1146 fix(avatar): dynamic icon sizes
  components/avatar/avatar.vue
  components/avatar/avatar_constants.js
Labels: visual-test-ready

#1152 fix(unread-pill): contrasting unread messages
  recipes/leftbar/unread_pill/unread_pill.vue
Labels: visual-test-ready

#1153 fix(unread-pill): contrasting unread messages - vue3
  recipes/leftbar/unread_pill/unread_pill.vue
Labels: visual-test-ready

#1150 docs(callbox): variants and docs
  common/assets/chatting-person-example.png
  percy.config.cjs
  recipes/leftbar/callbox/callbox.mdx
  recipes/leftbar/callbox/callbox.stories.js
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_constants.js
  recipes/leftbar/callbox/callbox_variants.story.vue
  recipes/leftbar/callbox/index.js
Labels: visual-test-ready

#1151 docs(callbox): variants and docs - vue3
  common/assets/chatting-person-example.png
  percy.config.cjs
  recipes/leftbar/callbox/callbox.mdx
  recipes/leftbar/callbox/callbox.stories.js
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_constants.js
  recipes/leftbar/callbox/callbox_variants.story.vue
  recipes/leftbar/callbox/index.js
Labels: visual-test-ready

#1154 fix(leftbar-row): corrected selected row's foreground color
  recipes/leftbar/style/leftbar_row.less
Labels: visual-test-ready

#1155 fix(leftbar-row): corrected selected row's foreground color - vue3
  recipes/leftbar/style/leftbar_row.less
Labels: visual-test-ready
