Repository dialpad/dialtone-vue, pull requests merged in 2023-09, with the labels that each got.

#1158 test(callbox): add tests
  recipes/leftbar/callbox/callbox.test.js
  recipes/leftbar/callbox/callbox.vue
Labels: no-visual-test

#1159 test(callbox): add tests - vue3
  recipes/leftbar/callbox/callbox.test.js
  recipes/leftbar/callbox/callbox.vue
Labels: no-visual-test

#1136 feat(message-input): emoji suggestion
  components/rich_text_editor/extensions/emoji/EmojiList.vue
  components/rich_text_editor/extensions/emoji/emoji.js
  components/rich_text_editor/extensions/emoji/suggestion.js
  components/rich_text_editor/rich_text_editor.vue
  package-lock.json
  package.json
Labels: visual-test-ready

#1156 test(combobox, datepicker, dropdown): new test template
  .github/TEST_CONTRIBUTING/TEST_GUIDELINE.md
  components/combobox/combobox.test.js
  components/datepicker/datepicker.test.js
  components/dropdown/dropdown.test.js
Labels: no-visual-test

#1157 test(combobox, datepicker, dropdown): new test template - vue3
  .github/TEST_CONTRIBUTING/TEST_GUIDELINE.md
  components/combobox/combobox.test.js
  components/datepicker/datepicker.test.js
  components/dropdown/dropdown.test.js
Labels: no-visual-test

#1135 feat: feed item pill recipe
  recipes/conversation_view/feed_pill/feed_item_pill.mdx
  recipes/conversation_view/feed_pill/feed_item_pill.stories.js
  recipes/conversation_view/feed_pill/feed_item_pill.test.js
  recipes/conversation_view/feed_pill/feed_item_pill.vue
  recipes/conversation_view/feed_pill/feed_item_pill_constants.js
  recipes/conversation_view/feed_pill/feed_item_pill_default.story.vue
  recipes/conversation_view/feed_pill/index.js
Labels: visual-test-ready

#1162 test(emoji, emoji-text-wrapper, image-viewer): new test template
  components/emoji/emoji.test.js
  components/emoji/emoji.vue
  components/emoji_text_wrapper/emoji_text_wrapper.test.js
  components/image_viewer/image_viewer.test.js
Labels: no-visual-test

#1163 test(emoji, emoji-text-wrapper, image-viewer, emoji-picker): new test template - vue3
  components/emoji/emoji.test.js
  components/emoji/emoji.vue
  components/emoji_picker/emoji_picker.test.js
  components/emoji_text_wrapper/emoji_text_wrapper.test.js
  components/image_viewer/image_viewer.test.js
Labels: no-visual-test

#1168 fix(image-viewer): fix close icon not visible on dark mode
  components/image_viewer/image_viewer.vue
Labels: visual-test-ready

#1169 fix(image-viewer): fix close icon not visible on dark mode vue3
  components/image_viewer/image_viewer.vue
Labels: visual-test-ready

#1166 test(input, input-group, item-layout, keyboard-shortcut): new test template
  components/input/input.test.js
  components/input_group/input_group.test.js
  components/item_layout/item_layout.test.js
  components/keyboard_shortcut/keyboard_shortcut.test.js
Labels: no-visual-test

#1167 test(input, input-group, item-layout, keyboard-shortcut): new test template - vue3
  components/input/input.test.js
  components/input_group/input_group.test.js
  components/item_layout/item_layout.test.js
  components/keyboard_shortcut/keyboard_shortcut.test.js
Labels: no-visual-test

#1170 fix(feed-item,feed-item-row): fix avatar alignment
  recipes/conversation_view/feed_item_row/feed_item_row.vue
Labels: visual-test-ready

#1171 fix(feed-item,feed-item-row): fix avatar alignment
  recipes/conversation_view/feed_item_row/feed_item_row.vue
Labels: visual-test-ready

#1175 feat(leftbar-row): add new icon color for contact center type
  recipes/leftbar/general_row/general_row_constants.js
Labels: visual-test-ready

#1164 feat: add `avatar-click` event in contact info
  recipes/list_items/contact_info/contact_info.mdx
  recipes/list_items/contact_info/contact_info.stories.js
  recipes/list_items/contact_info/contact_info.vue
  recipes/list_items/contact_info/contact_info_default.story.vue
Labels: visual-test-ready

#1177 feat(message-input): add focus method
  recipes/conversation_view/message_input/message_input.test.js
  recipes/conversation_view/message_input/message_input.vue
  recipes/conversation_view/message_input/message_input_default.story.vue
Labels: vue3-only, visual-test-ready

#1174 test(link, list-item, list-item-group): new test template - vue3
  components/link/link.test.js
  components/list_item/list_item.test.js
  components/list_item_group/list_item_group.test.js
Labels: no-visual-test

#1173 test(link, list-item, list-item-group): new test template
  components/link/link.test.js
  components/list_item/list_item.test.js
  components/list_item_group/list_item_group.test.js
Labels: no-visual-test

#1165 feat: add avatar click event in contact info (vue3)
  recipes/list_items/contact_info/contact_info.mdx
  recipes/list_items/contact_info/contact_info.stories.js
  recipes/list_items/contact_info/contact_info.vue
  recipes/list_items/contact_info/contact_info_default.story.vue
Labels: visual-test-ready

#1180 fix: feed pill not exported
  index.js
Labels: visual-test-ready

#1181 fix: feed pill not exported
  index.js
Labels: visual-test-ready

#1182 fix(avatar): change avatar seed algorithm to sync with android
  common/utils.js
  components/avatar/avatar.test.js
  components/avatar/avatar_constants.js
  package-lock.json
  package.json
Labels: visual-test-ready

#1185 fix(avatar): change avatar seed algorithm to sync with android
  common/utils.js
  components/avatar/avatar.test.js
  components/avatar/avatar_constants.js
  package-lock.json
  package.json
Labels: visual-test-ready

#1176 feat(avatar): add clickable behavior
  components/avatar/avatar.mdx
  components/avatar/avatar.stories.js
  components/avatar/avatar.test.js
  components/avatar/avatar.vue
  components/avatar/avatar_default.story.vue
  components/avatar/avatar_variants.story.vue
Labels: visual-test-ready

#1183 fix(recipe-callbar-button-with-popover): change event name and sync open state
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover.stories.js
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover.test.js
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover.vue
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover_default.story.vue
Labels: visual-test-ready

#1184 fix(recipe-callbar-button-with-popover): change event name and sync open state - Vue3
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover.stories.js
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover.test.js
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover.vue
  recipes/buttons/callbar_button_with_popover/callbar_button_with_popover_default.story.vue
Labels: visual-test-ready

#1188 feat(avatar): add clickable behavior - vue3
  components/avatar/avatar.mdx
  components/avatar/avatar.stories.js
  components/avatar/avatar.test.js
  components/avatar/avatar.vue
  components/avatar/avatar_default.story.vue
  components/avatar/avatar_variants.story.vue
Labels: visual-test-ready

#1186 fix(contact-info, feed-item-row, item-layout): alignment issues
  components/item_layout/item_layout.vue
  recipes/conversation_view/feed_item_row/feed_item_row.test.js
  recipes/conversation_view/feed_item_row/feed_item_row.vue
  recipes/list_items/contact_info/contact_info.vue
Labels: visual-test-ready

#1194 fix(item-layout): selected slot alignment
  components/item_layout/item_layout.vue
Labels: visual-test-ready

#1195 fix(item-layout): selected slot alignment - vue 3
  components/item_layout/item_layout.vue
Labels: visual-test-ready

#1192 fix: add virtual "prompt" for visual tests on PR
  .github/CONTRIBUTING.md
  .github/workflows/visual_tests.yml
  docs/templates/pr_template.mdx
Labels: visual-test-ready

#1193 fix: add virtual "prompt" for visual tests on PR
  .github/CONTRIBUTING.md
  .github/workflows/visual_tests.yml
  docs/templates/pr_template.mdx
Labels: no-visual-test

#1196 feat(callbox): add clickable behavior
  components/avatar/avatar.vue
  components/avatar/avatar_variants.story.vue
  recipes/leftbar/callbox/callbox.mdx
  recipes/leftbar/callbox/callbox.stories.js
  recipes/leftbar/callbox/callbox.test.js
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_default.story.vue
  recipes/leftbar/callbox/callbox_variants.story.vue
Labels: visual-test-ready

#1178 test(modal, notice, pagination): new test template - vue3
  components/modal/modal.test.js
  components/notice/notice.test.js
  components/pagination/pagination.test.js
Labels: no-visual-test

#1179 test(modal, notice, pagination): new test template
  components/modal/modal.test.js
  components/notice/notice.test.js
  components/pagination/pagination.test.js
Labels: no-visual-test

#1197 feat(callbox): add clickable behavior - vue3
  components/avatar/avatar.stories.js
  components/avatar/avatar.vue
  components/avatar/avatar_variants.story.vue
  recipes/leftbar/callbox/callbox.mdx
  recipes/leftbar/callbox/callbox.stories.js
  recipes/leftbar/callbox/callbox.test.js
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_default.story.vue
  recipes/leftbar/callbox/callbox_variants.story.vue
Labels: visual-test-ready

#1200 chore: update storybook to 7.4.2
  components/chip/chip_variants.story.vue
  package-lock.json
  package.json
  recipes/leftbar/callbox/callbox_variants.story.vue
Labels: visual-test-ready

#1198 fix(contact-row): add space between presence and status text
  recipes/leftbar/contact_row/contact_row.vue
  recipes/leftbar/style/leftbar_row.less
Labels: vue3-only, visual-test-ready

#1205 chore(modal): export modal banner kinds
  components/modal/index.js
Labels: no-visual-test

#1206 chore(modal): export modal banner kinds
  components/modal/index.js
Labels: no-visual-test

#1208 fix(modal): export modal banner kinds
  components/modal/index.js
Labels: no-visual-test

#1210 fix(callbox): video height
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_variants.story.vue
Labels: visual-test-ready

#1211 fix(callbox): video height
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_variants.story.vue
Labels: visual-test-ready

#1190 fix: emoji row css
  recipes/conversation_view/emoji_row/emoji_row.stories.js
  recipes/conversation_view/emoji_row/emoji_row.vue
Labels: visual-test-ready

#1201 test(popover, presence, radio): new test template
  components/popover/popover.test.js
  components/presence/presence.test.js
  components/radio/radio.test.js
Labels: no-visual-test

#1204 test(radio-group, root-layout, scroller): new test template - vue3
  components/radio_group/radio_group.test.js
  components/root_layout/root_layout.test.js
  components/scroller/scroller.test.js
Labels: no-visual-test

#1212 feat(attachment-carousel): Image thumbnail with progress bar for the attachment carousel.
  recipes/conversation_view/attachment_carousel/attachment_carousel.stories.js
  recipes/conversation_view/attachment_carousel/attachment_carousel.vue
  recipes/conversation_view/attachment_carousel/attachment_carousel_default.story.vue
  recipes/conversation_view/attachment_carousel/media_components/image_carousel.vue
  recipes/conversation_view/attachment_carousel/media_components/progress_bar.vue
Labels: no-visual-test

#1220 fix(message-input): emoji picker to insert the emoji node into editor
  recipes/conversation_view/message_input/message_input.vue
Labels: no-visual-test

#1221 fix(list-item): apply correct color design tokens
  components/list_item/list_item.vue
Labels: visual-test-ready

#1223 fix(list-item): apply correct color design tokens - vue3
  components/list_item/list_item.vue
Labels: visual-test-ready

#1218 fix(callbox, avatar): events and styling
  components/avatar/avatar.vue
  package-lock.json
  package.json
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_variants.story.vue
Labels: visual-test-ready

#1219 fix(callbox, avatar): events and styling
  components/avatar/avatar.vue
  package-lock.json
  package.json
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_variants.story.vue
Labels: visual-test-ready

#1225 feat(callbox): on hold status
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_default.story.vue
  recipes/leftbar/callbox/callbox_variants.story.vue
Labels: visual-test-ready

#1226 feat(callbox): on hold status
  recipes/leftbar/callbox/callbox.vue
  recipes/leftbar/callbox/callbox_default.story.vue
  recipes/leftbar/callbox/callbox_variants.story.vue
Labels: visual-test-ready

#1224 fix: address feedItemRow and feedItemPill css issues vue3
  recipes/conversation_view/feed_item_row/feed_item_row.stories.js
  recipes/conversation_view/feed_item_row/feed_item_row.vue
  recipes/conversation_view/feed_item_row/feed_item_row_default.story.vue
  recipes/conversation_view/feed_item_row/feed_item_row_variants.story.vue
  recipes/conversation_view/feed_pill/feed_item_pill.vue
Labels: no-visual-test

#1215 fix: address feedItemRow and feedItemPill css issues
  recipes/conversation_view/feed_item_row/feed_item_row.stories.js
  recipes/conversation_view/feed_item_row/feed_item_row.vue
  recipes/conversation_view/feed_item_row/feed_item_row_default.story.vue
  recipes/conversation_view/feed_item_row/feed_item_row_variants.story.vue
  recipes/conversation_view/feed_pill/feed_item_pill.vue
Labels: visual-test-ready
