Repository dialpad/dialtone-vue, pull requests merged in 2023-01, with the labels that each got.

#676 feat(tooltip): add contentAppear prop
  components/tooltip/tooltip.vue
  components/tooltip/tooltip_default.story.vue
Labels: vue3-only

#685 fix(popover): blocking wheel event vue3
  components/popover/popover.vue
Labels: no-visual-test

#683 fix(popover): blocking wheel event
  components/popover/popover.vue
Labels: no-visual-test

#688 fix(popover): refactor wheel event
  components/popover/popover.vue
Labels: no-visual-test

#689 fix(popover): refactor wheel event - vue 3
  components/popover/popover.vue
Labels: no-visual-test

#697 fix(collapsible): fix validation of anchor-related prop and slot
  components/collapsible/collapsible.vue
Labels: vue2-only

#704 feat: include CHANGELOG files in the package
  CHANGELOG.json
  package-lock.json
  package.json
  release-local.config.js
Labels: no-visual-test

#705 feat: include CHANGELOG files in the package
  CHANGELOG.json
  package-lock.json
  package.json
  release-local.config.js
Labels: no-visual-test

#708 fix(popover): blocking wheel event
  components/popover/popover.vue
Labels: no-visual-test

#709 fix(popover): blocking wheel event - vue 3
  components/popover/popover.vue
Labels: no-visual-test

#710 fix(root-layout): detect empty slot
  common/utils.js
  components/root_layout/root_layout.vue
  components/root_layout/root_layout_default.story.vue
  components/tooltip/tooltip.vue
Labels: vue3-only, no-visual-test

#711 feat: css as separate file
  README.md
  package.json
  vue.config.js
Labels: vue3-only, no-visual-test

#712 feat(semantic-release): add vue3 releases to GitHub releases
  release-ci.config.js
  release-local.config.js
Labels: vue3-only, no-visual-test

#715 fix(notice): incorrect validation
  components/notice/notice.stories.js
  components/notice/notice_action.test.js
  components/notice/notice_action.vue
Labels: no-visual-test

#716 fix(notice): incorrect validation - vue 3
  components/notice/notice.stories.js
  components/notice/notice_action.test.js
  components/notice/notice_action.vue
Labels: no-visual-test
