Repository dialpad/dialtone-vue, pull requests merged in 2023-05, with the labels that each got.

#950 fix(header): fix exports
  index.js
  recipes/header/settings_menu_button/settings_menu_button.vue
Labels: visual-test-ready

#951 fix(header): fix exports
  index.js
  recipes/header/settings_menu_button/settings_menu_button.vue
Labels: visual-test-ready

#952 fix(recipe-grouped-chip): grouped chip width and content style fixes.
  recipes/chips/grouped_chip/grouped_chip.stories.js
  recipes/chips/grouped_chip/grouped_chip.vue
Labels: visual-test-ready

#949 fix(recipe-grouped-chip): grouped chip width and content style fixes.
  recipes/chips/grouped_chip/grouped_chip.stories.js
  recipes/chips/grouped_chip/grouped_chip.vue
Labels: visual-test-ready

#954 feat: add tests for feed row
  recipes/conversation_view/feed_item_row/feed_item_row.test.js
  recipes/conversation_view/feed_item_row/feed_item_row.vue
Labels: visual-test-ready

#957 fix: add tests for feed row - vue3
  recipes/conversation_view/feed_item_row/feed_item_row.test.js
  recipes/conversation_view/feed_item_row/feed_item_row.vue
Labels: visual-test-ready

#953 docs(rich-text-editor): link extension tech spec
  components/rich_text_editor/rich_text_editor.tech_spec.md
Labels: no-visual-test

#973 fix: bundle in vue
  vite.config.js
Labels: vue3-only, no-visual-test
