Repository dialpad/dialtone-vue, pull requests merged in 2023-02, with the labels that each got.

#733 chore(deps): update @dialpad/conventional-changelog-angular package
  package-lock.json
  package.json
Labels: no-visual-test

#735 chore(deps): update @dialpad/conventional-changelog-angular package
  package-lock.json
  package.json
Labels: no-visual-test

#747 chore: update dialtone icons
  package-lock.json
  package.json
Labels: no-visual-test

#748 chore: update dialtone-icons - vue 3
  package-lock.json
  package.json
Labels: no-visual-test

#757 test: disable css animation on lazy_show while testing
  components/collapsible/collapsible.test.js
  components/collapsible/collapsible_lazy_show.vue
  components/lazy_show/lazy_show.vue
Labels: vue2-only, no-visual-test

#756 fix(collapsible): pass only listeners to lazy show
  common/utils.js
  components/collapsible/collapsible.test.js
  components/collapsible/collapsible.vue
  components/collapsible/collapsible_lazy_show.vue
  components/lazy_show/lazy_show.vue
  recipes/comboboxes/combobox_with_popover/combobox_with_popover.test.js
Labels: vue3-only, no-visual-test

#760 chore: update dialtone-icons and extract into constant
  components/icon/icon.vue
  components/icon/icon_constants.js
  package-lock.json
  package.json
Labels: no-visual-test

#761 chore: update dialtone-icons and extract into constant - vue 3
  components/icon/icon.vue
  components/icon/icon_constants.js
  package-lock.json
  package.json
Labels: no-visual-test
